apiVersion: v1
kind: Service
metadata:
  name: {{ include "vigil-controller.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "vigil-controller.labels" . | nindent 4 }}
  {{- with .Values.metricsService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
  - name: http
    port: {{ .Values.metricsService.port }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "vigil-controller.selectorLabels" . | nindent 4 }}
